version: '3.7'

services:
  nextjs:
    build:
      context: .  # Chỉ định thư mục chứa Dockerfile của bạn
    container_name: nextjs-app
    ports:
      - "3000:3000"  # Mở cổng 3000 để có thể truy cập vào Next.js từ bên trong container
    labels:
      - "traefik.enable=true"  # Kích hoạt Traefik cho service này
      - "traefik.http.routers.nextjs.rule=Host(`coinfe.trungthanhdev.com`) && PathPrefix(`/traefik`)"  # Định nghĩa rule cho routing Traefik
      - "traefik.http.services.nextjs.loadbalancer.server.port=3000"  # Cổng mà Next.js đang chạy trong container
      - "traefik.http.routers.nextjs.entrypoints=websecure"  # Sử dụng entrypoint HTTPS
      - "traefik.http.routers.nextjs.tls=true"  # Bật TLS cho HTTPS
    networks:
      - traefik  # Kết nối container Next.js với network traefik

networks:
  traefik:
    external: true  # Đảm bảo Traefik và các dịch vụ container sử dụng cùng mạng này
